---
roles:
  - name: geerlingguy.docker
    version: 7.1.0

  - name: geerlingguy.nfs
    version: 2.0.0

#  - name: roles-ansible.restic

  - name: borgbase.ansible_role_borgbackup

collections:
  - name: ansible.posix
  - name: community.docker
  - name: community.general
  - name: vladgh.samba
